allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9ac76186-ea5b-4562-82eb-e104b942d28e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-15T21:35:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 37b5455b-b8e5-4796-a62e-db01cc25fa9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1bce15eb-e441-43c8-bff3-cb4b0197fef2 # Hero Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0cd0860-ac38-4ebf-bd11-49d8430935e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2f20dc2-c4c9-4db3-b571-b6bd29b3c472
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e7aad41d-ba44-478d-90e0-02389f7524fa # Button
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6259657-ddbc-4a15-a911-4a088a12533d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fba1ff8e-0b24-45ff-8403-da24499dfef2 # buttonLink
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f963b9c-84c8-44b1-a4ba-8305a890545e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82e1b15c-fda6-4a34-95c4-725ea725857b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 489aa9de-78dd-4788-80c7-9307d470bb57 # Main Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 437c2ff0-271b-4981-b6e8-45090c6289ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2063caa-51e7-4867-9faf-e44087a75bcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e0c16f-f27c-40ca-b911-0f9728a92db1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e1bf3b3c-4ca1-4e7b-9e98-64e3052a587a # Hero Image
            handle: heroImage2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 916594c0-852e-4057-822f-1809678d8097
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9bdc992e-fe2b-4e1d-926a-01d9a7b5772d # Info Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc1c35ed-ea1b-4b4d-a90e-c508a67e100e
            userCondition: null
            warning: null
            width: 100
        name: Strategies
        uid: ba6e3896-69b1-4b3e-8c85-6cfb2c02113a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f9501fa8-ddf7-45c9-848a-c7ece198f27a # Paragraph Heading
            handle: paragraphHeading2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26b79621-d1be-4d3c-8697-606fa012ec64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 38fb1215-8745-4b26-a4bc-fa81375d8e56 # Guide PDF
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e0c3dfb-5773-4efd-a401-0d514e54adae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4c9973ff-0107-4739-a889-f352e62eca08 # Large Paragraph
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c7a7a8d-2cc5-4bc2-a36d-1524f24e4fb7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ba8d40a-8645-41c3-8eca-34dd285b2c5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T22:24:54+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4768ec2a-8f50-4698-80e6-75c7975086db # Email Message Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c0e48cf-3e7d-43e8-9eaf-4033ab34a92c
            userCondition: null
            warning: null
            width: 100
        name: 'Lead Magnet (Get the Guide)'
        uid: a40b904f-926e-4e77-84b5-444575a17847
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cbd26eb9-425b-4f80-b796-58d777f40b96 # Main Headline
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5b210f0-1938-46ac-b750-b46035c235d3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4c9973ff-0107-4739-a889-f352e62eca08 # Large Paragraph
            handle: largeParagraph2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b740a4f6-bf1e-411d-98a9-17449edfc3f9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T21:46:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 383dafac-19c3-4559-9459-54a9919aada4 # Body Text
            handle: bodyText3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48199a67-1e4d-4156-a28e-8ab44aab461f
            userCondition: null
            warning: null
            width: 100
        name: 'Thank You Page'
        uid: af70fa31-e3b2-47a0-baad-2f78b26f85af
        userCondition: null
    thumbFieldKey: null
handle: landingPages
hasTitleField: true
icon: null
name: 'Landing Pages'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
