css: "[\r\n  {\r\n    \"name\": \"Aligned List\",\r\n    \"element\": \"ul\",\r\n    \"styles\": {\r\n      \"padding-left\": \"25px\",\r\n      \"list-style-position\": \"outside\"\r\n    }\r\n  }\r\n]"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  alignment:
    options:
      - left
      - right
  indentBlock:
    offset: 40
    unit: px
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - link
  - bulletedList
  - numberedList
  - alignment
  - outdent
  - indent
