altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  450c7a7f-d093-479b-9eff-4ee794d9f753:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-16T05:20:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: df0088b9-d09b-4386-9cdd-8a99fa7a780e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-16T05:21:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d88c44ab-26ea-420e-a97d-8430b93e3aa9 # Hero Image Optimized
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d38f3fae-27ed-470b-a095-9f8f79a1b5cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d063f1b-6fb3-45b5-99a1-2e74d4eadc96
        userCondition: null
    thumbFieldKey: null
fs: foxplanAssets
handle: testOptimisedVolume
name: 'test optimised volume'
sortOrder: 7
subpath: test-images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: foxplanTransforms
transformSubpath: test-images
